### ISSUE TITLE
Documentation of use

### ISSUE THREAD

**Issue by camachojua** [Emiller88/emacs-jest#11]
I've been trying to use your package without good results, for the installation I'm using `use-package` in this way:

```elisp
;; Jest mode
(use-package jest
  :ensure t
  :config
  (setq jest-executable "npm run test --"))

(use-package add-node-modules-path
  :ensure t)
```

When I'm editing a test file and after executing `M-x jest-popup t` I get the following message in the minibuffer:

```elisp
Wrong type argument: stringp, nil
```
My `package.json` looks like this:

```json
"scripts": {
    "test": "jest"
  }
```
Could anyone provide me help on this configuration issue?

**Comment by edmundmiller** [comment]
@camachojua Sorry I hadn't gotten back to this! I've started using https://github.com/avajs/ava over jest, personally. I have some thoughts to generalize this to run with any test suite but it's pretty low on my todolist. 

The first pass was rough and relys on jest being globally installed(From the issues I've read) I think a better general solution would be to use the npm `test`scripts and `test:` for partial runs.
