### ISSUE TITLE
Turn on colors by default

### ISSUE THREAD

**Issue by cprussin** [Emiller88/emacs-jest#19]
Any reason why colors are disabled by default and would you be amenable to adding an option to enable them by default?

**Comment by edmundmiller** [comment]
I'm not opposed, could you PR it and post a before and after screenshot?

**Comment by cprussin** [comment]
Absolutely, will get to it soon

**Comment by cprussin** [comment]
Went to implement this and while reading up on `magit-popup` I realized that the macro already expands to create a variable that can be used for this:

```elisp
(setq jest-arguments '("--colors"))
```

So I don't think there's anything to be done in `emacs-jest` here.  Thanks anyways!
