### ISSUE TITLE
Support jest-function for Typescript-mode

### ISSUE THREAD

**Issue by davazp** [Emiller88/emacs-jest#22]
The `jest-function` uses js2, so it does not work on other modes like typescript-mode.

A few ideas:
- one option could be to just add code to get the same information from other modes.
- another one could be to have some basic heuristics and not rely on js2-mode at all.  So using some basic regular expressions to extract the path of describe/it strings.
- Maybe another libraries like like `lsp`, `imenu`, could be used?

**Comment by lazyskulptor** [comment]
I made a function extracting test name from buffer. Please check and give some advices to improve. 

https://github.com/Emiller88/emacs-jest/pull/25

**Comment by PierreRambaud** [comment]
is it possible to go further with this PR, it's really interesting?
If the maintainer is not able to test and do something, maybe some people are interesting to help :)

**Comment by edmundmiller** [comment]
> is it possible to go further with this PR, it's really interesting? If the maintainer is not able to test and do something, maybe some people are interesting to help :)

Thanks for reviewing that! I haven't been writing much JS myself recently, so I haven't been using it. 

I used this repo to test however in case that's of use in the future, so we can reproduce results https://github.com/Lemoncode/jest-testing-by-sample/tree/master/frontend/02%20Plain%20Vanilla

**Comment by lazyskulptor** [comment]
> is it possible to go further with this PR, it's really interesting?
> If the maintainer is not able to test and do something, maybe some people are interesting to help :)

Thanks for review. I found some bugs on my code.
When there are special symbols in test name, It doesn't work. 
ASAP I will try to fix it.
