### ISSUE TITLE
Use compilation-shell-minor-mode

### ISSUE THREAD

**Issue by sandinmyjoints** [Emiller88/emacs-jest#3]
Activating compilation-shell-minor-mode will enable the all the cool features of compilation-mode, for example, compilation-next-error, compilation-previous-error, and compile-goto-error. So you quickly go to a failing test and jump from its stack trace directly to the failed assertion.

**Comment by edmundmiller** [comment]
@sandinmyjoints Would you be interested in submitting a PR for this?

**Comment by sandinmyjoints** [comment]
@Emiller88 Sure, I will try to get to it soon. In the meantime, I've been just using `(add-hook 'jest-mode-hook #'compilation-minor-mode)` and it works fine. (I found that compilation-minor-mode had more of the key bindings I was expecting than compilation-shell-minor-mode.)

BTW, I've also written a jest-minor-mode that I use to have access to the `jest-*` commands when in different kinds of buffers. It's got some rough edges but I would like to polish it up and submit it as well. I love this package and use it almost daily at work!

**Comment by edmundmiller** [comment]
I believe #12 fixes this.
