### ISSUE TITLE
jest-function generates invalid jest command line

### ISSUE THREAD

**Issue by gaetano-guerriero** [Emiller88/emacs-jest#5]
When `jest--current-defun` finds a function jest is called with a command line like `jest file.test.js::functionName`. To my understanding the `::` syntax is unknown to jest so matching tests will never be found. jest ` --testNamePattern=<regex>` should be used instead.

**Comment by edmundmiller** [comment]
@gaetano-guerriero I think that's residual from emacs-python-pytest. I'll see about changing that or you can submit a PR for the specific change.
