### ISSUE TITLE
Feature request: per project jest-arguments

### ISSUE THREAD

**Issue by sandinmyjoints** [Emiller88/emacs-jest#7]
For example, at work we have different jest config files for different repos. Because jest-arguments is global, when I save a config file for a particular repo, it is not only the default for that repo but also for other repos.

**Comment by edmundmiller** [comment]
@sandinmyjoints I think this will be fixed by #2. I'm not currently using jest for testing in any projects, so I'm not dog fooding it, though I wish I was. Feel free to open a PR if you find a fix!

A hack might be setting the jest-arguments in `.dir-locals.el` in the project root.

**Comment by baerrach** [comment]
Use https://github.com/Emiller88/emacs-jest/issues/2#issuecomment-522308399

```
(use-package jest
  :config
  (setq jest-executable "npm test --")
)
```

Then you can put your configuration into `package.json` per project.

**Comment by edmundmiller** [comment]
@baerrach I like that option, but then we're opening up to mocha for example, which is fine I just don't know if the flags will work for that.

**Comment by baerrach** [comment]
The magic `--` flag just mean pass whatever comes after it to the actual expansion of the script.

**package.json**
```
  "scripts": {
    "test": "cross-env NODE_PATH=. jest",
```

So when you run `npm test -- <args>` it will get expanded to `cross-env NODE_PATH=. jest <args>`.

Change the scripts from
```
    "test": "cross-env NODE_PATH=. jest",
```
to
```
    "test": "mocha",
```

and it will be expanded to `mocha <args>`

**Comment by edmundmiller** [comment]
Thanks for the detailed explanation.

What I meant though was the pop-up flags don't match up across jest and mocha just
as an example.

https://mochajs.org/#command-line-usage

https://jestjs.io/docs/en/cli.html

Which wouldn't be a problem for the jest users it would be an issue for the
mocha users trying to use `emacs-jest`

This actually got me thinking that a universal test runner for emacs would be
cool based on this idea from pytest. Similar to `format-all-the-code` but the
issue would be getting every test runners flags automatically.

**Comment by baerrach** [comment]
Right, its my first day using `emacs-jest` so I'm not using the popup other than to fiddle with it...
