### ISSUE TITLE
Running `jest-file` subsequently results in `jest--run-as-comint: Text is read-only` message

### ISSUE THREAD

**Issue by bi1yeu** [Emiller88/emacs-jest#8]
Running `jest-file` against a test file works as expected, but only once. If the compilation buffer exists, subsequently running `jest-file` does not result in the tests being run. The `*Messages*` buffer simply contains `jest--run-as-comint: Text is read-only`.

**Comment by sandinmyjoints** [comment]
I am now running into this, too.

**Comment by sandinmyjoints** [comment]
This turned to be caused by some other packages I use setting `comint-prompt-read-only` to `t`. I made it buffer-local and now things work fine:

```lisp
  (make-variable-buffer-local 'comint-prompt-read-only)
  (setq-default comint-prompt-read-only nil)
```

**Comment by edmundmiller** [comment]
@sandinmyjoints Great! Could you open a PR to fix it?

**Comment by catesandrew** [comment]
works here, please merge
